currency_converter/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, DecimalField, SubmitField

class ConvertForm(FlaskForm):
    """convert from to convert amount from base to taret currency"""

    available_currencies = [('EUR', 'EUR Euro'),
                            ('USD', 'US Dollar'),
                            ('JPY', 'JPY Japanese Yen')]

    base_currency = SelectField('base_currency',
                                choices=available_currencies)
    base_amount = DecimalField('base_amount',
                               places=None)
    target_currency = SelectField('target_currency',
                                  choices=available_currencies)

    submit = SubmitField('Submit')

currency_converter/app.py
from flask import Flask
from flask_bootstrap import Bootstrap

def create_app():
    app = Flask(__name__)
    app.config.from_object("currency_converter.settings")

    from .views import currency_converter
    app.register_blueprint(currency_converter)
    Bootstrap(app)

    return app

currency_converter/views.py
from flask import Blueprint, render_template, request, flash

from forex_python.converter import CurrencyRates

from .forms import ConvertForm

currency_converter = Blueprint('currency_converter', __name__)

@currency_converter.route('/convert', methods=['GET', 'POST'])
def convert():
    """convert amount from base to target currency"""
    form = ConvertForm(request.form)
    has_result = False
    target_amount = False
    has_csrf_token = hasattr(form, 'csrf_token')
    if request.method == 'POST':
        if form.validate_on_submit():
            has_result = True

            try:
                CR = CurrencyRates()
                target_amount = CR.convert(form.base_currency.data,
                                           form.target_currency.data,
                                           form.base_amount.data)
            except Exception:
                # TODO: test with testing framework
                flash('currency conversion API failed', 'warning')
        else:
            flash('Form could not be validated. See below', 'warning')

    return render_template('convert.html',
                           form=form,
                           has_result=has_result,
                           target_amount=target_amount,
                           has_csrf_token=has_csrf_token)

currency_converter/templates/convert.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
      <!-- Categories: success (green), info (blue), warning (yellow), danger (red) -->
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <!-- <strong>Title</strong> --> {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <h2>Currency Converter</h2>
    <form action="{{ url_for('currency_converter.convert') }}" method="post" class="form" role="form">
      {% if has_csrf_token %}
          {{ form.csrf_token() }}
      {% endif %}
     <d1>
      {{ wtf.form_field(form.base_amount, class='form-control', placeholder='42.42') }}      
      {{ wtf.form_field(form.base_currency, class='form-control') }}
      {{ wtf.form_field(form.target_currency, class='form-control') }} 
     </d1>     
     <p><input type=submit class='btn btn-warning btn-block'>
    </form>
</div>

{% if has_result %}
<div class="container">
    <h3>Converted Currency</h2>

    {{form.base_amount.data}} {{form.base_currency.data}} = {{target_amount}} {{form.target_currency.data}}
</div>
{% endif %}

{% endblock %}